disabled_rules:
  - force_try
  - line_length
  - nesting
type_name:
  excluded:
    - iCookTVKeys
    - iCookTVTests
variable_name:
  excluded:
    - id
    - URL
excluded:
  - Carthage
  - Pods
  - iCookTV/R.generated.swift
